--- #YAML:1.0
name: Maypole-Plugin-Session
version: 0.1
author:
  - David Baird <cpan@riverside-cms.co.uk>
abstract: simple sessions for Maypole
license: perl
requires:
  CGI::Simple::Cookie: 0
  Maypole: 2
  Test::More: 0
  URI: 0
provides:
  Maypole::Plugin::Session:
    file: lib/Maypole/Plugin/Session.pm
    version: 0.1
generated_by: Module::Build version 0.2609
