--- #YAML:1.0
name: Maypole-Plugin-Session
version: 0.2
author:
  - David Baird <cpan@riverside-cms.co.uk>
abstract: simple sessions for Maypole
license: perl
requires:
  Apache::Session::Wrapper: 0.24
  Maypole: 2
  Test::More: 0
provides:
  Maypole::Plugin::Session:
    file: lib/Maypole/Plugin/Session.pm
    version: 0.2
generated_by: Module::Build version 0.2609
